services:
  vlm:
    container_name: vlm
    build: .
    ports:
      - 3000:3000
    #volumes:
      #  - .:/app
      #- ./node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: npm start
    restart: unless-stopped

networks:
  default:
    external: true
    name: hwangbro
